name = "Assembly Language Server"
version = "0.1.0"
authors = ["Jacob Parker <blocckba5her@gmail.com>"]
description = "Assembly syntax highlighting and language server"
repository = "https://github.com/DevBlocky/zed-asm"
id = "assembly"
schema_version = 1

[grammars.asm]
repository = "https://github.com/RubixDev/tree-sitter-asm"
commit = "04962e15f6b464cf1d75eada59506dc25090e186"

[language_servers.asm-lsp]
name = "asm-lsp"
languages = ["Assembly"]
